apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: backstage
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
      - name: app-config-rhdh
    extraEnvs:
      envs:
        - name: NODE_EXTRA_CA_CERTS
          value: /extraFiles/ca.crt
      secrets:
        - name: rhdh-secrets
    extraFiles:
      mountPath: extraFiles
      secrets:
        - name: backstage-tls
          key: ca.crt
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true